source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0'
gem 'puma', '~> 3.0'
gem 'pg', '~> 0.20.0'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'haml-rails', '~> 0.9'
gem 'coffee-rails', '~> 4.2'

gem 'jquery-rails', '~> 4.3.1'
gem 'jquery-ui-rails', '~> 6.0.1'
gem 'turbolinks', '~> 5'
gem 'jbuilder', '~> 2.5'
gem 'redis', '~> 3.0'

gem 'devise', '~> 4.2'
gem 'omniauth', '~> 1.6.1'
gem 'omniauth-marvin', '~> 1.0', '>= 1.0.2'
gem 'omniauth-facebook', '~> 4.0'
gem 'omniauth-twitter', '~> 1.2', '>= 1.2.1'
gem 'omniauth-google-oauth2', '~> 0.4.1'

gem 'inherited_resources', github: 'lambda2/inherited_resources'
gem 'cancan', '~> 1.6.10'
gem 'simple_form', '~> 3.4.0'
gem 'simple-form-datepicker', '~> 0.1.3'
gem 'active_model_serializers', '~> 0.10.0'
gem 'awesome_print', '~> 1.7.0'
gem 'kaminari', '~> 1.0.1'

gem 'carrierwave', '~> 0.11.2'
gem 'carrierwave-ffmpeg', '~> 1.0.0'
gem 'carrierwave_backgrounder', '0.4.2'
gem 'carrierwave-video', '0.5.6'
gem 'carrierwave-video-thumbnailer', '0.1.4'
gem 'rmagick', '~> 2.16.0'

gem 'bootstrap', '~> 4.0.0.alpha3'
gem 'font-awesome-rails', '~> 4.7.0.1'
gem 'flag-icons-rails', '~> 1.1.2'
gem 'switchery-rails', '~> 0.8.1.1'
gem 'streamio-ffmpeg', ref: 'c84b8cf405fa', github: 'streamio/streamio-ffmpeg', branch: 'master'
gem 'sidekiq', '~> 4.2.10'
gem 'sidekiq-failures', '~> 0.4.5'
gem "sidekiq-cron", "~> 0.4.0"

gem 'imdb', github: 'D1ceWard/imdb', branch: 'master'
gem 'subdb', '~> 0.1.6'
gem 'rails-i18n', '~> 5.0.3'
gem 'hyper_torrent', github: 'D1ceWard/hyper_torrent', branch: 'master'

gem 'foreman', '~> 0.84.0'

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  gem 'better_errors'
  gem 'binding_of_caller'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
